artifacts_config:
  artifacts_directory: artifacts

data_ingestion_config:  
  dataset_download_url: https://files.grouplens.org/datasets/movielens/ml-latest-small.zip
  dataset_directory: dataset
  ingested_directory: ingested
  raw_data_directory: raw_data